<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Info_penukaran_point_model extends CI_Model
{

    public $table = 'info_penukaran_point';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('daftar_untuk_penukaran_point', $q);
	$this->db->or_like('konfirmasi_penukaran', $q);
	$this->db->or_like('batas_akhir_konfirmasi', $q);
	$this->db->or_like('pengiriman', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('daftar_untuk_penukaran_point', $q);
	$this->db->or_like('konfirmasi_penukaran', $q);
	$this->db->or_like('batas_akhir_konfirmasi', $q);
	$this->db->or_like('pengiriman', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Info_penukaran_point_model.php */
/* Location: ./application/models/Info_penukaran_point_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-06 12:01:17 */
/* http://harviacode.com */